# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@1
  displayName: 'Build an image'

#- script: |
#    docker-compose -f docs/docker-compose.yml --project-directory . -p docs up -d
#    docker wait docs_sut_1
#    docker-compose -f docs/docker-compose.yml --project-directory . down
